[package]
name = "reproducer-wmi-windows-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.9.0"
windows = "0.20.1"

[build-dependencies]
windows = "0.20.1"

